name: Build and publish Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: test
        run: echo $GITHUB_ACTOR

      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Codeceptjs test
        run: |
          cd e2e
          npm install
          npx codeceptjs run --steps
          cd ..
        env:
          CI: true

      - name: Build Docker image (includes mvn clean package)
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u Naludrag --password-stdin
          docker build -t rockandstones/stoneoverflow docker/images/stoneoverflow
          docker tag rockandstones/stoneoverflow ghcr.io/rockandstones/stoneoverflow
          docker push ghcr.io/rockandstones/stoneoverflow