name: Build and publish Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo $GITHUB_ACTOR

      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image (includes mvn clean package)
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u b3cauda --password-stdin
          docker build -t amt/stoneoverflow
          docker tag amt/stoneoverflow ghcr.io/amt/stoneoverflow
          docker push ghcr.io/amt/stoneoverflow